# Sources of information:
# https://game.ci/docs/github/builder/
# https://game.ci/docs/github/getting-started#workflow-examples
# https://github.com/game-ci/unity-builder/issues/241
# https://game.ci/docs/troubleshooting/common-issues/#branch-is-dirty

name: Build and Deploy WebGL

on:
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
    build:
        name: Build WebGL
        runs-on: ubuntu-latest
        steps:
            # Checkout without Git LFS
            - name: Checkout repository
              uses: actions/checkout@v4

            # Git LFS
            - name: Create LFS file list
              run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id
            
            - name: Restore LFS cache
              uses: actions/cache@v3
              id: lfs-cache
              with:
                path: .git/lfs
                key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}

            - name: Git LFS Pull
              run: |
                git lfs pull
                git add .
                git reset --hard

            # Cache/Use Unity Library files if available
            - name: Prepare Unity cache
              uses: actions/cache@v3
              with:
                path: ./unity-project/mini-game-collection/Library
                key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
                restore-keys: |
                  Library-

            # Test
            #- name: Run Unity tests
            #  uses: game-ci/unity-test-runner@v4
            #  env:
            #    UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
            #    UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
            #    UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
            #  with:
            #    githubToken: ${{ secrets.GITHUB_TOKEN }}
            #    projectPath: ./unity-project/mini-game-collection/

            # Create build
            #- name: Build project (WebGL)
            #  uses: game-ci/unity-builder@v4
            #  env:
            #    UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
            #    UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
            #    UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
            #  with:
            #    # Temporary workaround while LFS dirtying issue persists
            #    allowDirtyBuild: true
            #    buildsPath: ./build
            #    buildMethod: UnityBuilderAction.BuildScript.Build
            #    # Parameters to pass to buildMethod if required
            #    #customParameters:
            #    projectPath: ./unity-project/mini-game-collection/
            #    targetPlatform: WebGL
            #    unityVersion: auto
            #    versioning: Semantic

            # Output / store build
            #- uses: actions/upload-artifact@v4
            #  with:
            #    name: Build
            #    path: ./build

            # Push build to GitHub pages
            #- name: Setup Pages
            #  uses: actions/configure-pages@v5

            #- name: Upload artifact
            #  uses: actions/upload-pages-artifact@v4
            #  with:
            #    path: ./build/WebGL/WebGL/

            #- name: Deploy to GitHub Pages
            #  id: deployment
            #  uses: actions/deploy-pages@v4

            # TEST - speed up iteration by skipping build
            - name: TEST - Create test artifacts
              run: |
                mkdir ./build
                mkdir ./build/WebGL
                mkdir ./build/WebGL/WebGL
                touch ./build/WebGL/WebGL/sample.txt

            # Create zip of build
            - name: Build project
              # zip <output> <input>
              run: |
                export ZIP_NAME="mini-game-collection-$(date +"%Y-%m-%d").zip"
                zip ZIP_NAME ./build/WebGL/WebGL/
                echo "Archive created: $ZIP_NAME"
                echo $ZIP_NAME >> $GH_ZIP_NAME
                ls

            # Release Timestamp
            - name: Create release timestamp
              run: |
                export BUILD_DATE="date"
                echo "Build time: $BUILD_DATE"
                echo $BUILD_DATE >> $GH_BUILD_DATE

            # Create release page
            - name: Create Release Page
              id: create_release_page
              uses: actions/create-release@v1
              env:
                 # This token is provided by Actions
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                tag_name: ci_${{ env.branch }}_${{ github.sha }}
                release_name: Release ci_${{ env.branch }} (${{ env.BUILD_DATE }})
                body: |
                  Automatic build release generated on ${{ env.BUILD_DATE }}.
                  GitHub ref: ${{ github.ref }}
                  Commit SHA hash: ${{ github.sha }}
                draft: false
                prerelease: true
                
            # Upload artifacts to release page
            - name: Upload Release Build
              id: upload-release-asset 
              uses: actions/upload-release-asset@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                # This pulls from the CREATE RELEASE step above, referencing
                # it's ID to get its outputs object, which include a `upload_url`.
                # See this blog post for more info:
                # https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
                upload_url: ${{ steps.create_release_page.outputs.upload_url }}
                asset_path: ${{ env.GH_ZIP_NAME }}
                asset_name: ${{ env.GH_ZIP_NAME }}
                asset_content_type: application/zip
              